# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc72715095da45f90c82be7a79dc8e442b5a9d19fb6df26134132b5691e24a26e6d95b876733568538685c69a70856452df89340c7d9dc7c30a1a23de1373e70

test:
  secret_key_base: 8e670eb372d8fcbac77fcc5df9087b8a31c8f960d914bf1100a6e668f6dff3ac83e3e0e4f6f5d26980b914d7d12ee17a2c8387fdea5a70729ff42a35216882fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
